### PR TITLE
Add languages doc page

### PR DESCRIPTION
**Pull request by strarsis**
@swalkinshaw:
This PR adds a new doc page about managing languages in a Composer-managed (Bedrock) site on Trellis.

### CODE REVIEW

**Comment by retlehs** [comment]
i've yet to need to do anything like this, but after reading i still don't understand the need for these trellis docs when there's already (that you linked):

* https://wp-languages.github.io/
* https://github.com/bjornjohansen/wplang
* https://github.com/Angrycreative/composer-plugin-language-update

this seems like a very opinionated approach that might be better suited for a guide? 

it would still be beneficial to add some language docs to bedrock, not trellis, that cover the composer specific options

**Comment by strarsis** [comment]
@retlehs: During some Trellis discussions the wish came up for a wiki (doc) page about managing languages. It would bundle all the stuff discussed in the forum so one can find what is recent and best practice.

Other things could be added like [Polylang](https://polylang.pro/), [WPML](https://wpml.org/de/) and [TranslatePress](https://translatepress.com/translate-gutenberg-blocks-in-wordpress/).
E.g. wIth the new Gutenberg editor TranslatePress got a very attractive Gutenblock-level translation feature. Or setting up an [intro page](https://github.com/strarsis/polylang-intro-page) with Polylang.

I agree though that in the current state the page only really outlines the opinionated approach using `wp` cli.

**Comment by odinho** [comment]
Though using the upstream approach is really a good method since anything would really be opinionated. The others seem even more so.

I was looking for this, thankfully I decided to surf around in the Git project looking for docs and found this, which seems like a really nice guide : )

**Comment by swalkinshaw** [comment]
Even though I agree with @retlehs  that this doesn't exactly classify as "documentation", I'd probably rather have this "guide" than not. Maybe we can just add a new Guides section and put this under it?

@strarsis is this content still accurate?

**Comment by strarsis** [comment]
@swalkinshaw: Yes, I am still using this setup and it works quite well. The WP CLI remark is still important, but now Trellis uses a newer one by default, so I think this can stay there.

There are some optimizations possible, but I don't know if they can be easily implemented.
Like switching/updating the language before changing the site symlink so there is no "flash of untranslated labels".
These improvements can still be added later on top. I often revisit old things and update them when I find out better practices.

**Comment by swalkinshaw** [comment]
Sounds good. I think you can just add a new "Guides" section to https://github.com/jonathanbossenger/roots-docs/blob/master/docs/trellis/master.js and assign this page to it as a `children`.

**Comment by strarsis** [comment]
@swalkinshaw: I have to make a new PR for this.

**Pull request closed without merging**
