### PR TITLE
Testing sync

### PR DESCRIPTION
**Pull request by retlehs**

### CODE REVIEW

**Comment by retlehs** [comment]
@mAAdhaTTah fyi just updated to latest ver - this update didn't sync back, and i can't force it via admin or wp-cli

**Comment by mAAdhaTTah** [comment]
@retlehs Thanks for the test. Can you check the webhook response in GitHub and see if there's any information there?

**Comment by retlehs** [comment]
didn't even think to check there!

```
{"success":false,"data":[{"code":"404_not_found","message":"Method GET to endpoint https:\/\/api.github.com\/repos\/roots\/docs\/git\/commits\/ failed with error: Not Found"}]}```

**Comment by retlehs** [comment]
that might be related to one of my wp-cli attempts. did another import from admin, waiting for the request to show up in github now but haven't seen anything yet

**Comment by mAAdhaTTah** [comment]
The request shows up in GitHub when new commits are added and sent to the website; if you're importing via wp-cli, it won't show there.

**Comment by mAAdhaTTah** [comment]
Can you post or email me the payload from that failed import? It looks like it's supposed to do a GET with the commit sha, but the sha is missing.

**Comment by retlehs** [comment]
after #9, the last 3 payloads show:

1. Invalid post ID - [payload](https://gist.github.com/retlehs/8b9ff2063423a72d50e8)
2. Invalid post ID - [payload](https://gist.github.com/retlehs/4e6eb3365e05733885e4)
3. Method GET to endpoint https:\/\/api.github.com\/repos\/roots\/docs\/git\/commits\/ failed with error: Not Found - [payload](https://gist.github.com/retlehs/1d64e6927bd416607fb6)

**Pull request merged**
