### PR TITLE
Clarify behavior of Disallow Indexing plugin

### PR DESCRIPTION
**Pull request by alwaysblank**
Mistakes setting `WP_ENV` can have SEO consequences, so a little advice here would likely not go amiss. 

This PR supervised by @MWDelaney.

### CODE REVIEW

**Comment by knowler** [comment]
I like this. Perhaps add a heading. Then we can add a **Learn More** link to the admin notice for roots/bedrock#369.

Search engine indexing has been discouraged because the current environment is development. Learn More

**Comment by QWp6t** [comment]
I think instead of focusing solely on "Disallow indexing" we could just stress the importance of making sure that `WP_ENV` is set correctly according to its environment. We use a [similar check in Soil](https://github.com/roots/soil/blob/master/modules/google-analytics.php#L19) as well, which disables Google Analytics if the environment is non-production, and [we used to check `WP_ENV` in Sage](https://github.com/roots/sage/blob/7.0.3/lib/scripts.php#L22). I've seen plugins in the wild that also look for the value of `WP_ENV`. And obviously Bedrock itself makes use of it when loading environment-specific configurations and setting other global constants.

So I'm thinking we could reword these docs to stress the importance of correctly setting `WP_ENV`, and we can refactor https://github.com/roots/bedrock/pull/369 to create a new mu-plugin that lets devs know when the environment is not production.

**Comment by swalkinshaw** [comment]
I think it's two separate concerns. I agree we should have better docs around the environments and `WP_ENV`.

But right now it's still pretty transparent and hidden that we disallow robots for indexing purposes. That being said, does it even matter? No one wants it for dev/staging.

Maybe another useful mu-plugin is one that shorts the env by default in the WP top bar?

**Comment by JulienMelissas** [comment]
There is this: https://roots.io/plugins/stage-switcher/, but in my opinion, this might come down to an improvement in the docs about environments. I don't think the stage switcher should be baked in.

**Comment by runofthemill** [comment]
there are a few browser plugins that the docs could link to; there was a really good one I recall seeing that added a subtle border around the browser viewport, color tied to the environment. I can't find it now but here are two similar ones I just found for Chrome:

https://chrome.google.com/webstore/detail/environment-marker/ahjhdebcnlgmojdmjnhikhakkghcchkk?hl=en-US

https://chrome.google.com/webstore/detail/environment-switcher/eeealghlapdbddajndpopjjkbgccbjfl?hl=en-US

**Pull request merged**
