### PR TITLE
Useful information about vault files

### PR DESCRIPTION
**Pull request by MikeiLL**
and access recovery.

### CODE REVIEW

**Comment by tangrufus** [comment]
Questions about "Access Recovery": 

- Does `$ sudo passwd admin` work if I don't have the sudo password?
- Does `UPDATE mysql.user .....` work if I don't have the MySQL root password?

Or, a better question - is there anyway to find those 2 passwords on the server?

**Comment by MikeiLL** [comment]
That is a great question. In a DO droplet you can reset the root password via the web interface. My guess is that strong passwords cannot be recovered on a unix system, by design. If these contributions to the docs make sense, maybe they also need to mention that a reset of the root password might be necessary.

**Comment by tangrufus** [comment]
It would be nice to mention the DigitalOcean feature and (maybe) links to tutorials about how to restore EC2 from snapshots. 

It's worth mentioning that we can use `$ wp db export` and `$ wp db import` to move the db on to new servers. And, some `rsync` examples to move media files.

But we leave them in another PR.

**Review by tangrufus — APPROVED** [review]

**Comment by MikeiLL** [comment]
> It would be nice to mention the DigitalOcean feature and (maybe) links to tutorials about how to restore EC2 from snapshots.

I like that idea. Is EC2 Amazon's answer to DO droplets?

> It's worth mentioning that we can use `$ wp db export` and `$ wp db import` to move the db on to new servers. And, some `rsync` examples to move media files.

Yes. There is some [banter about adding rsync](https://github.com/roots/trellis-cli/issues/109#issuecomment-796452792) to trellis-cli as well.

**Comment by swalkinshaw** [comment]
Agreed this is useful 👍  thanks

**Pull request merged**
