### PR TITLE
Add deploy_keep_releases to wordpress_sites options

### PR DESCRIPTION
**Pull request by dalepgrant**

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🤔 this is a valid WP site option, but I'd prefer this live in https://roots.io/trellis/docs/deploys/#. What do you think?

It's an option that's more likely to be set globally rather than differ per site.

**Comment by dalepgrant** [comment]
I did think about that myself as that’s where I went looking for it initially. I ended up adding it to Options as that’s where it looks like you’re listing all available options, which is the second place I went looking. Could add it to both, if you’d prefer?

**Comment by dalepgrant** [comment]
Second thoughts: I’m not sure it would necessarily be a more global thing. We have sites that we regularly push changes to and ones that we update once a month or less.

**Comment by swalkinshaw** [comment]
Interesting! Anyway, this is a valid option so no harm in adding it. Thanks 😄

**Comment by swalkinshaw** [comment]
If you want to add something to the Deploy docs then that would be welcomed too

**Comment by dalepgrant** [comment]
Done! 👍

**Pull request merged**
