### PR TITLE
Update remote-server-setup.md

### PR DESCRIPTION
**Pull request by rhetthenckel**
Fixes a gap in the server docs.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🤔 yeah not sure what happened here but obviously something is wrong. I'm not sure about this update though either; the order/flow still seems weird. I'll think on it.

**Comment by swalkinshaw** [comment]
Thanks for opening this @rhetthenckel, it made me go over a lot of these docs again. I opened https://github.com/roots/docs/pull/422 as a larger effort to improve them.

Here's the preview for it: https://deploy-preview-422--hardcore-pike-9e5241.netlify.app/trellis/master/remote-server-setup/

Does that look better?

**Comment by rhetthenckel** [comment]
Oh wow, yes, much better flow and very clear. Thanks @swalkinshaw! 
Yeah I was looking for best place to mention Ubuntu kernel / package maintenance or suggest considering using [the HWE stack](https://wiki.ubuntu.com/Kernel/LTSEnablementStack) or at least be familiar with the [ubuntu release cycle](https://ubuntu.com/about/release-cycle#ubuntu) ... not sure if that wants to live here or maybe Digging Deeper section.

**Comment by swalkinshaw** [comment]
@rhetthenckel a new page under the Basics category would probably work.

**Pull request closed without merging**
