### PR TITLE
Add git setup instructions to installing-trellis.md

### PR DESCRIPTION
**Pull request by partounian**
Whenever this is refined/confirmed as okay, I will also update the trellis readme.

(removed the $ to allow easier copy-pasting)

### CODE REVIEW

**Comment by retlehs** [comment]
this makes things a lot more confusing for a new user, which is the last thing we want to do.

we can possibly add a new page to the docs for upgrading trellis, and link to the relevant threads on roots discourse where it's been discussed.

**Comment by partounian** [comment]
Imo this makes it more understandable. When I start any programming project, I like to get it into version control immediately, and currently the docs for getting Trellis into git are just not there. There are some sparse docs about using subtrees but that is much more confusing and doesn't do anything but give merge conflicts for every single change.

**Comment by MWDelaney** [comment]
The tone of the Roots docs are intended to show you how to use the Roots tools without digging too far into the supporting software.

We've included Git environmental setup instructions on in the new [getting started docs](https://roots.io/getting-started/docs/), but I think that's as opinionated as we want to be about how users set up their version control.

**Comment by partounian** [comment]
Sure, whatever floats your boat 😄

**Pull request closed without merging**
