### PR TITLE
About the prompt not showing on Windows

### PR DESCRIPTION
**Pull request by xaliber**
Added information from here https://discourse.roots.io/t/setting-up-sage-9-with-uikit/11652

### CODE REVIEW

**Comment by retlehs** [comment]
use WSL

**Comment by xaliber** [comment]
I was trying to add information from Discourse on how to trigger the prompt on Windows.

Even with WSL, I think that information (of using WSL) should be added on the docs for Windows users, as it is not immediately obvious. Just trying to help other (possible) confused users like me.

**Comment by Log1x** [comment]
The docs only recommends WSL in it's current state.

https://roots.io/getting-started/docs/windows-basic-setup/

**Comment by xaliber** [comment]
Ah, you're right. I came from this page

https://roots.io/sage/

straight to the "Theme installation". Didn't realize there was another page for Windows basic setup.

**Pull request closed without merging**
