### PR TITLE
Adding docksal link.

### PR DESCRIPTION
**Pull request by danshumaker**
Docksal now supports Bedrock.

### CODE REVIEW

**Comment by swalkinshaw** [comment]
Thanks!

**Comment by danshumaker** [comment]
@swalkinshaw  Is there another deploy necessary?  I'm not seeing the change on https://roots.io/docs/bedrock/master/local-development/#additional-resources.

**Comment by swalkinshaw** [comment]
Do a hard refresh and you should see it. Our docs site uses service workers for caching so normal refreshes won't see updates (until some point in time afaik)

**Comment by danshumaker** [comment]
Ah, right you are.  The update is there.   I dont know why it continues to amaze me how hard browseres hold on to thier caches.

**Pull request merged**
